# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.8'

services:
  proyecta_webapi_dotnet_dev:
    image: proyecta-webapi-dotnet
    container_name: proyecta-webapi-dotnet-dev
    ports:
      - "8000:443"
      - "8001:80"
    environment:
      - ConnectionStrings__AppDbConnection=Host=proyecta_db_postgres;Database=proyecta_app_db
      - ConnectionStrings__AuthDbConnection=Host=proyecta_db_postgres;Database=proyecta_auth_db
      - ASPNETCORE_ENVIRONMENT=Development
      - PROYECTA_WEBAPI_DEVELOPMENT_DB_USER=${PROYECTA_WEBAPI_DEVELOPMENT_DB_USER}
      - PROYECTA_WEBAPI_DEVELOPMENT_DB_PASSWORD=${PROYECTA_WEBAPI_DEVELOPMENT_DB_PASSWORD}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PROYECTA_WEBAPI_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${PROYECTA_WEBAPI_CERT_PATH}
    volumes:
      - ${HOME}/.aspnet/https:/https/
    #  - ~/.vsdbg:/remote_debugger:rw
    networks:
      - proyecta-network

networks:
  proyecta-network:
    external: true