# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  webapi:
    image: proyectacontainerregistry.azurecr.io/proyecta_webapi:latest
    ports:
      - "80:80"
      - "443:443"