# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  webapi_dotnet:
    image: proyecta_webapi_dotnet_dev
    container_name: 'proyecta_webapi_dotnet_dev'
    build:
      context: .
      dockerfile: Proyecta.Web/Dockerfile-dev
    ports:
      - "8000:443"
      - "8001:80"
    environment:
      - ConnectionStrings__DbConnection=${PROYECTA_WEBAPI_DB_CONNECTION}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PROYECTA_WEBAPI_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${PROYECTA_WEBAPI_CERT_PATH}
    volumes:
      - ${HOME}/.aspnet/https:/https/
    #  - ~/.vsdbg:/remote_debugger:rw
    networks:
      - proyecta_network

networks:
  proyecta_network: