# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.8'

services:
  proyecta_api_dotnet_dev:
    image: proyecta/api-dotnet
    container_name: proyecta_api_dotnet_dev
    ports:
      - "${HTTP_PORT:-5000}:80"  # Maps host's HTTP_PORT or default 5000 to port 80 in the container
      - "${HTTPS_PORT:-5001}:443" # Maps host's HTTPS_PORT or default 5001 to port 443 in the container
    environment:
      # By default, ASP.NET Core applications recognize three environments: Development, Staging, and Production.
      - ASPNETCORE_ENVIRONMENT=Development
      - PROYECTA_DB_CONNECTION_API=${PROYECTA_DB_CONNECTION_API}
      - PROYECTA_DB_CONNECTION_AUTH=${PROYECTA_DB_CONNECTION_AUTH}
      - PROYECTA_API_USER_SYSTEM_PASSWORD=${PROYECTA_API_USER_SYSTEM_PASSWORD}
      - PROYECTA_API_USER_ADMIN_PASSWORD=${PROYECTA_API_USER_ADMIN_PASSWORD}
      - ConnectionStrings__AppDbConnection=${PROYECTA_DB_CONNECTION_API}
      - ConnectionStrings__AuthDbConnection=${PROYECTA_DB_CONNECTION_AUTH}
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${PROYECTA_API_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${PROYECTA_API_CERT_PATH}
    volumes:
      - ${HOME}/.aspnet/https:/https/
    #  - ~/.vsdbg:/remote_debugger:rw
    networks:
      - proyecta-network

networks:
  proyecta-network:
    external: true