version: '3.4'

services:
  db_postgres:
    image: postgres
    container_name: 'proyecta_db_postgres'
    environment:
      - POSTGRES_DB=${PROYECTA_DB_POSTGRES_DB}
      - POSTGRES_USER=${PROYECTA_DB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${PROYECTA_DB_POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - proyecta_network

volumes:
  pgdata:
    
networks:
  proyecta_network: